version: "3.9"
services:
  db:
    image: postgres:16
    container_name: chordspace_db
    restart: unless-stopped
    env_file:
      - db/.env.db
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-ChordCodex}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
volumes:
  db_data:
