
import numpy as np
import matplotlib.pyplot as plt

# Constants from config.py for Sethares model
Dstar = 0.24
S1 = 0.0207
S2 = 18.96
C1 = 5
C2 = -5
A1 = -3.51
A2 = -5.75
BASE_FREQ = 261.63 # C4

# Standalone function based on _calcular_disonancia_pairwise from pre_process.py
def calcular_disonancia_pairwise(f1, f2, a1, a2):
    Fmin = np.minimum(f1, f2)
    S = Dstar / (S1 * Fmin + S2)
    Fdif = np.abs(f2 - f1)
    a = np.minimum(a1, a2)
    return a * (C1 * np.exp(A1 * S * Fdif) + C2 * np.exp(A2 * S * Fdif))

# Generate data for the curve
f1 = BASE_FREQ
f2_range = np.linspace(f1, 2 * f1, 500) # Sweep one octave
dissonance = [calcular_disonancia_pairwise(f1, f2, 1.0, 1.0) for f2 in f2_range]

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(f2_range, dissonance)
plt.title('Sethares Dissonance Curve (Generated by Gemini)')
plt.xlabel('Frequency of second note (Hz)')
plt.ylabel('Dissonance')
plt.grid(True)
plt.savefig('sethares_curva_gemini.png')
print("Plot generated and saved as sethares_curva_gemini.png")
