-- Canonical schema for the ChordCodex dataset consumed by ChordSpace.
-- Applies cleanly on first run and is idempotent for existing installations.

CREATE TABLE IF NOT EXISTS chords (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    n SMALLINT NOT NULL,
    interval INTEGER[] NOT NULL,
    notes TEXT[] NOT NULL,
    bass TEXT,
    octave SMALLINT,
    frequencies DOUBLE PRECISION[],
    chroma DOUBLE PRECISION[],
    tag TEXT,
    code TEXT,
    span_semitones SMALLINT,
    abs_mask_int BIGINT,
    abs_mask_hex TEXT,
    notes_abs_json TEXT
);

-- Align legacy installations (created before v0.2.0) with the canonical schema.
ALTER TABLE chords
    ALTER COLUMN interval TYPE INTEGER[] USING interval::INTEGER[],
    ALTER COLUMN notes TYPE TEXT[] USING notes::TEXT[],
    ADD COLUMN IF NOT EXISTS span_semitones SMALLINT,
    ADD COLUMN IF NOT EXISTS abs_mask_int BIGINT,
    ADD COLUMN IF NOT EXISTS abs_mask_hex TEXT,
    ADD COLUMN IF NOT EXISTS notes_abs_json TEXT;

-- Unique constraints expected by chordcodex.scripts.db_fill_v2
CREATE UNIQUE INDEX IF NOT EXISTS idx_chords_unique_abs_mask_int
    ON chords (abs_mask_int);

CREATE UNIQUE INDEX IF NOT EXISTS idx_chords_unique_n_notes_interval
    ON chords (n, notes, interval);

-- Helpful covering index for interval-based filters used across experiments.
CREATE INDEX IF NOT EXISTS idx_chords_interval
    ON chords USING GIN (interval);
